version: '3'
services:
    webserver:
        image: trafex/php-nginx:latest
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html:delegated
        ports:
        -   "80:8080"
    mariadb:
        image: 'mariadb:latest'
        ## expose the mysql port to our machine so we can access it from any mysql-client like TablePlus ##
        ports:
            - "4306:3306"
        ## keep mysql data on localhost so we don't lose them ##
        volumes:
            - ./tools/docker-volumes-data/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: docker-test
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
    redis:
        image: redis
        volumes:
            ## keep redis data on localhost so we don't lose them ##
            - ./tools/docker-volumes-data/redis:/data
